# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PTKegZP90a1xRA-A9UtkqHRRBEjq8XQK
"""

import pandas as pd

hmps = pd.read_csv('HollywoodsMostProfitableStories.csv', encoding='latin1')

hmps

hmps.info()

hmps.describe

check = hmps.isnull().sum()

check

cleaned_df = hmps.dropna()

cleaned_df

print(cleaned_df.isnull().sum())

cleaned_df.dtypes

cleaned_df['Audience  score %']=cleaned_df['Audience  score %'].astype(int)

cleaned_df['Rotten Tomatoes %']=cleaned_df['Rotten Tomatoes %'].astype(int)

cleaned_df.dtypes

cleaned_df.rename(columns={'Audience  score %': 'Audience Score %'})

cleaned_df.to_csv('Cleaned_File.csv', index=False)